Repository codegasms/sisyphus, pull requests merged in 2024-10, with the labels that each got.

#1 Implement a simple TCP listener
  README.md
  main.go
Labels: documentation, enhancement

#2 Define strategy enum, structs and their constructors
  strategy.go
Labels: enhancement

#3 Implement config loading from a JSON file
  .gitignore
  config.go
  main.go
  strategy.go
Labels: enhancement

#4 Implement round robin strategy
  strategy.go
Labels: enhancement

#5 Implement random strategy
  strategy.go
Labels: enhancement

#6 Implement weighted round robin strategy
  strategy.go
Labels: enhancement

#7 Implement least connection strategy
  strategy.go
Labels: enhancement

#8 Add normalisation of weights in weighted round robin strategy
  strategy.go
Labels: enhancement

#9 Implement the load balancer core logic
  main.go
  strategy.go
Labels: enhancement

#11 Initialize server and load tester packages
  .gitignore
  Makefile
  README.md
  cmd/summit/main.go
  cmd/zeus/main.go
Labels: documentation, enhancement

#12 Make the second io.Copy call blocking
  main.go
Labels: bugfix

#13 Changing the order of io.Copy somehow fixes the connection not getting closed
  main.go
  strategy.go
Labels: bugfix

#14 Feat/ip hash
  main.go
  strategy.go
Labels: enhancement

#15 Implement a brutal load tester
  cmd/zeus/main.go
Labels: enhancement

#16 Fix connections not closing due to Keep-Alive in the load tester
  cmd/summit/main.go
  cmd/zeus/main.go
  main.go
Labels: bugfix

#17 Implement weighted least connection strategy
  strategy.go
Labels: enhancement

#18 LB Config instruction
  README.md
  main.go
Labels: documentation, bugfix
